### ISSUE TITLE
Host under a subdomain

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau-html#1]
Would it be possible to host Github Pages from this repository under a subdomain? Right now it deploys to https://metanorma.github.io/mn-samples-plateau-html/, but unfortunately the site relies to be hosted under domain root right now, so `/mn-samples-plateau-html/` breaks HTML.

It’d be nice to have for a demo this week.

**Comment by ronaldtse** [comment]
@strogonoff a subdomain only works for demo — MLIT hosts pages under their domain so you will have the same problem. It would be much better if you use non absolute paths.

**Comment by strogonoff** [comment]
I’m not sure using relative paths when referencing site-wide CSS at root level from a page 9 levels deep in the hierarchy is a good idea… At that point I’d rather use absolute paths, and build can support specifying deployment prefix. However, we’ll see, maybe relative paths will be acceptable.

Whether they host standards under a separate domain or not, we need to discuss the deployment plan with MLIT team, but I can’t do it unless someone can translate technical stuff between English and Japanese.

**Comment by ronaldtse** [comment]
Look at the existing site. That is how they will deploy.

**Comment by strogonoff** [comment]
Which one, this? https://www.mlit.go.jp/plateaudocument/. This is not “how they deploy”, this is the result. 
  
1. It’s not exactly representative. This is only one document, but they have multiple (and Metanorma allegedly handles at least two of them). Their URL schema will change to accommodate a collection of documents. It is not unreasonable to assume they might want to put that collection under a subdomain.

2. We should discuss with them how they will deploy & ways of integrating the build into their infrastructure.
 
   - If they use GHA, they would likely want to host on Github Pages (in which case, by the way, almost certainly they’ll provision a subdomain).
   - If they don’t use GHP or GHA, we should be on the same page on what they use or what they can use.

3. How they want to present the docs & integrate into the rest of their Web presence, and how they build it (all with Metanorma or they use something else for other docs), may affect whether we’ll want to use MN collection mechanism or not.

**Comment by ronaldtse** [comment]
There’s nothing to argue about here. There is a second document. Check carefully. The problem is paths in the static site. Assume they will deploy to the same paths. They will likely not use GHP at this stage.

**Comment by strogonoff** [comment]
If they don’t use GHP, absolutely we should discuss how they will build it and in what environment. This is part of the deliverable.

**Comment by strogonoff** [comment]
Anyway, this issue is about hosting this under a subdomain for the upcoming meeting. How they deploy (including the specifics) is something I’d like to discuss on that meeting, if someone can translate, but it’s not such a pressing issue.

**Comment by ronaldtse** [comment]
@strogonoff it is highly likely that no one can answer the question "where will the site be deployed" in the upcoming meeting... And it's okay.

**Comment by strogonoff** [comment]
Fair enough, though on the last meeting there were some technical people as far as I can tell (albeit they did not speak in English).

**Comment by kwkwan** [comment]
CNAME record `firelight.metanorma.org` has been setup to host GHP.
